plugins {
    id 'java'
    id 'application'
}

repositories { mavenCentral() }

application { mainClass = 'com.redemaissocial.Main' }

dependencies {
    implementation 'com.sparkjava:spark-core:2.9.4'
    implementation 'com.sparkjava:spark-template-thymeleaf:2.7.1'
    implementation 'org.thymeleaf:thymeleaf:3.1.2.RELEASE'
    implementation 'com.h2database:h2:2.3.232'
    implementation 'org.mindrot:jbcrypt:0.4'
    implementation 'org.slf4j:slf4j-simple:2.0.16'
}