# H2 Database Config
spring.datasource.url=jdbc:h2:file:./data/redemaisdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cria/atualiza tabelas automaticamente (perfeito para dev)
spring.jpa.hibernate.ddl-auto=update

# Ativa o console web do H2 em http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
